spring:
  application:
    name: shop
  mail:
    host: ${MAIL_SENDER_HOST}
    port: ${MAIL_SENDER_PORT}
    username: ${MAIL_SENDER_USERNAME}
    password: ${MAIL_SENDER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mail:
  from: ${MAIL_FROM}
kafka:
  bootstrapAddress: localhost:29092
  topics:
    order: order
logging:
  level:
    root: info
monitoring:
  api:
    url: ${SPLUNK_URL}
    token: ${SPLUNK_TOKEN}
    sourceType: _json