apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderProduct
spec:
  selector:
    matchLabels:
      app: orderProduct
  replicas: 1
  template:
    metadata:
      labels:
        app: orderProduct
    spec:
      containers:
        - name: orderProduct
          image: 891376971673.dkr.ecr.eu-west-3.amazonaws.com/shop-app:latest
          ports:
            - containerPort: 8090
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: orderProduct
spec:
  type: LoadBalancer
  selector:
    app: orderProduct
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8090